---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yt-api-charts.fullname" . }}-secrets
type: Opaque
data:
  YT_API_KEY: "{{ .Values.youtubeStatsSettings.ytApiKey | default "" | b64enc }}"
